name: prueba
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1  # Añade esta línea
  sqflite: ^2.0.0+3
  path: ^1.8.3
  #Dependencias de Firebase
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.11
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
