// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjTsAnwYEwJdqz7I0ZV5W9nNuK0xoyW6Y',
    appId: '1:932356837036:web:f2eb1f3f06777cb4d1d909',
    messagingSenderId: '932356837036',
    projectId: 'prueba-6d758',
    authDomain: 'prueba-6d758.firebaseapp.com',
    storageBucket: 'prueba-6d758.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdYMth4VdcN9YOkDd2-jC-ii0ALS0_Iko',
    appId: '1:932356837036:android:916db709cbe1a1c8d1d909',
    messagingSenderId: '932356837036',
    projectId: 'prueba-6d758',
    storageBucket: 'prueba-6d758.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqjpEnIZ6tkW39wnzEhinWqeMnTsyiV_0',
    appId: '1:932356837036:ios:af448ce3155cabecd1d909',
    messagingSenderId: '932356837036',
    projectId: 'prueba-6d758',
    storageBucket: 'prueba-6d758.firebasestorage.app',
    iosBundleId: 'com.example.prueba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqjpEnIZ6tkW39wnzEhinWqeMnTsyiV_0',
    appId: '1:932356837036:ios:af448ce3155cabecd1d909',
    messagingSenderId: '932356837036',
    projectId: 'prueba-6d758',
    storageBucket: 'prueba-6d758.firebasestorage.app',
    iosBundleId: 'com.example.prueba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjTsAnwYEwJdqz7I0ZV5W9nNuK0xoyW6Y',
    appId: '1:932356837036:web:8a9846191756764dd1d909',
    messagingSenderId: '932356837036',
    projectId: 'prueba-6d758',
    authDomain: 'prueba-6d758.firebaseapp.com',
    storageBucket: 'prueba-6d758.firebasestorage.app',
  );

}